### PR TITLE
Resolves #43 partly

### LINKED ISSUE #43: Generating bindings for Vulkan 1.0.25 fails
I don't know enough about the format used in the vk.xml file, however it seems that generating bindings for the latest revision of the Vulkan spec fails at WriteMemberArray because of being unable to find the 'len' member for a function pointer, specifically for pAcquireTimeoutMilliseconds: https://github.com/KhronosGroup/Vulkan-Docs/blob/1.0/src/spec/vk.xml#L2246

### PR DESCRIPTION
**Pull request by himanshugoel2797**

### CODE REVIEW

**Comment by himanshugoel2797** [comment]
Note: this doesn't build yet

**Comment by radekdoulik** [comment]
Hey @himanshugoel2797,

thanks for looking into this. I have fixed the build to work with the updated vk.xml spec meanwhile.

The part you are fixing should go to the Windows platform, so once you fix it, the VK_NV_external_memory_win32 extension should be added to the Windows platform (see https://github.com/mono/VulkanSharp/blob/master/tools/Generator/Generator.cs#L2066)

The unknown counters can be added to the fieldCounterMap  (see https://github.com/mono/VulkanSharp/blob/master/tools/Generator/Generator.cs#L472)

Please let me know if you are interested in finishing fixing it or if I should take a look at it.

**Comment by himanshugoel2797** [comment]
Ah sorry, I completely forgot about this, I'm sorry but I don't think I'll be able to finish this.

**Comment by radekdoulik** [comment]
Thanks for letting me know.

**Pull request closed without merging**
