### PR TITLE
Generator Update to better handle FlagBits + Extension

### PR DESCRIPTION
**Pull request by bholcomb**
This pull request changes the code generator for handling FlagBits when there is an extension after the type name.   This resolves issue #55.

### CODE REVIEW

**Comment by radekdoulik** [comment]
For some reason github didn't attach my comments to the relevant lines. Please look at https://github.com/bholcomb/VulkanSharp/commit/bd79df4eaf951ade714f924cad773f5f57167486 comments.

**Comment by bholcomb** [comment]
I made the requested changes in my branch, I think I got everything you were looking for.  Let me know if you would like me to change anything.  

I would like somebody to look at what I did for how the generator handles RROutput and Display structs since I wasn't quite sure what I did was the right thing.

**Comment by radekdoulik** [comment]
Thanks for the update.

I think it would be better to rename the new CheckFlagBitsName method to something like GetFlagBitsName because in current implementation it also returns the updated name.

Please also fix the method calls indentation and blocks indentation so that it looks like rest of the code. (so like `protected string CheckFlagBitsName (string name)` and the `{` braces on the same line as if, foreach, ...)

Please don't add new code to this PR and rather open new one for it (the Display, NN, ... changes).

It would also help if you could squash the generator changes to one patch and regenerated bindings to another. (use `git rebase -i`)

**Comment by bholcomb** [comment]
Opening a new pull request with a squashed commit

**Pull request closed without merging**
