### PR TITLE
Added windows plattform project and generator changes for windows

### PR DESCRIPTION
**Pull request by AlexHild**
Fixed version of #15.

### CODE REVIEW

**Comment by radekdoulik** [comment]
Thanks! The CLA bot is up again, could you please go and sign the copyright assignment on cla.xamarin.com? Let me know when you sign it so that I can merge the PR.

**Comment by AlexHild** [comment]
Just finished the copyright assignment, but did receive any email
notification. Did you receive it?

2016-06-01 21:06 GMT+02:00 Radek Doulik <notifications@github.com>:

**Comment by radekdoulik** [comment]
ah, I misread the cla-bot notification. Alex, could you please follow the link from the comment above and sign the CLA again. It looks like it wasn't recorded yesterday

**Comment by AlexHild** [comment]
I signed the CLA, but it seems my boss has not, yet. Will ask him as soon as I meet him.

**Comment by radekdoulik** [comment]
Alex, how does it look with the CLA, did you manage to finish it?

**Pull request merged**
